version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    restart: always

  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
