name: Github Actions Pipeline

on:
  push:
    branches:
      - main  # Change this if your default branch is different
  pull_request:
    branches:
      - main
      - jenkins

env:
  IMAGE_NAME: flask-app
  DOCKER_REGISTRY: docker.io  # Change if using AWS ECR, GCR, etc.

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: |
          pytest --junitxml=report.xml

  build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest .

      - name: Push Docker Image to Registry
        run: |
          docker push $DOCKER_REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy Application (Example Command)
        run: |
          echo "Deploying the application..."
          # Add actual deployment steps here, like SSHing into a server and running Docker Compose
